# Generated by Django 4.2.12 on 2024-05-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicAI', '0002_alter_patient_address_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_visit',
            old_name='perscription',
            new_name='prescription',
        ),
    ]
