# Generated by Django 4.2.12 on 2024-05-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicAI', '0003_rename_perscription_hospital_visit_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_visit',
            name='er_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital_visit',
            name='symptoms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
